### ISSUE TITLE
Fixes: Want to do UI fixes

### ISSUE THREAD

**Issue by ShahrozAhmd** [jeswanthmukesh20/online-clipboard#17]
There is an issue that once the user added the text and submits the test and added it then gets the retrieve id then the text box should be clear to add the new one.
The issue is I find that if the text area is not clear then the same content is added with as many ids as the user clicks on add button.

**Comment by ShahrozAhmd** [comment]
Hey 👋  @jeswanthmukesh20  kindly assign this issue to me

**Comment by jeswanthmukesh20** [comment]
@ShahrozAhmd Thank you for noticing that issue👍️

**Comment by ShahrozAhmd** [comment]
@jeswanthmukesh20  Thanks a lot  for assigning it to me 💯

**Comment by ShahrozAhmd** [comment]
@jeswanthmukesh20  
PR is up 👍

**Comment by ashwin3005** [comment]
The content vanishes suddenly, can you make a toast displaying that " your content is daved" in the text area?
